### PR TITLE
Support exclusiveMinimum and exclusiveMaximum

### LINKED ISSUE #378: Enhancement: Add More Spec Details to the UI
**Description:**
I've noticed that certain Swagger documentation annotations, notably 'minimum' and 'maximum', are present in the specification but are not reflected in the UI. Additionally, payloads with primitive types like 'string' don't have their type explicitly displayed in the UI.

**Steps to Reproduce:**

1. Add annotations like 'minimum' or 'maximum' to your Schema Annotation or use a primitive type as payload.
2. Verify they appear in the specification and note that 'type: string' (or similar) is present.
3. Observe the absence of these details in the UI.

**Expected Behavior:**
Swagger annotations, such as 'minimum' and 'maximum', would be a valuable addition to the UI. It would also be beneficial for the UI to display primitive types explicitly.

**Actual Behavior:**
Annotations are missing, and primitive types are not distinctly represented.

**Suggested Fix:**

Enhance the UI to incorporate Swagger annotations more comprehensively.
Display primitive payload types clearly.
Aim for parity with the display capabilities of the [AsyncAPI React component](https://github.com/asyncapi/asyncapi-react).

**Status:**

- [ ] Const
- [x] Enum
- [x] Items
- [x] MaxItems
- [x] MinItems
- [x] Required
- [x] name: String (default: "")
- [x] title: String (default: "")
- [x] multipleOf: double (default: 0.0)
- [x] maximum: String (default: "")
- [x] exclusiveMaximum: boolean (default: false)
- [x] minimum: String (default: "")
- [x] exclusiveMinimum: boolean (default: false)
- [x] maxLength: int (default: Integer.MAX_VALUE)
- [x] minLength: int (default: 0)
- [x] pattern: String (default: "")
- [ ] maxProperties: int (default: 0)
- [ ] minProperties: int (default: 0)
- [ ] requiredProperties: String[] (default: {})
- [ ] requiredMode: Schema.RequiredMode (default: Schema.RequiredMode.AUTO)
- [x] description: String (default: "")
- [x] format: String (default: "")
- [x] ref: String (default: "")
- [x] nullable: boolean (default: false)
- [x] example: String (default: "")
- [ ] externalDocs: ExternalDocumentation (default: @ExternalDocumentation)
- [ ] deprecated: boolean (default: false)
- [x] type: String (default: "")
- [ ] allowableValues: String[] (default: {})
- [ ] defaultValue: String (default: "")
- [ ] discriminatorProperty: String (default: "")
- [ ] hidden: boolean (default: false)
- [ ] enumAsRef: boolean (default: false)
- [x] types: String[] (default: {})
- [x] exclusiveMaximumValue: int (default: 0)
- [x] exclusiveMinimumValue: int (default: 0)

### PR DESCRIPTION
**Pull request by aerfus**
**Describe the feature request**
Support exclusiveMinimum and exclusiveMaximum in UI.

Resolves #378

### CODE REVIEW

**Comment by timonback** [comment]
Hi @aerfus ,
Creating an own angular component for this is a great refactoring.

Can you adapt the kafka example (dto + asyncapi.json) as well so that we can test this visually?

**Comment by timonback** [comment]
Thank you @aerfus. It is merged now.

FYI: I am preparing a capability to unit test components: https://github.com/springwolf/springwolf-core/pull/558

**Comment by aerfus** [comment]
> Thank you @aerfus. It is merged now.
> 
> FYI: I am preparing a capability to unit test components: #558

@timonback ,
sure, I wanted to cover the new component with test.
So I'm waiting for the merge of #558

**Comment by timonback** [comment]
No worries, I expect that we review&merge it next Friday.
I have no prior experience with testing in angular and default guide suggest the karma library. Feel free to adjust/improve tests or the test setup

**Comment by aerfus** [comment]
Hi @timonback ,
I've started working on tests for schema.component.ts.
Checkout was from timonback:test/add-jest-testing-to-springwolf-ui

**Pull request merged**
