### PR TITLE
test: use angular testing library for component tests

### PR DESCRIPTION
**Pull request by timonback**
- refactored 3 test as a start
- testing with actual (amqp) mock data (can be extended later)

### CODE REVIEW

**Comment by timonback** [comment]
Hi @aerfus Feel free to have a look and review. I am curious about your thoughts.

**Comment by aerfus** [comment]
Hi @timonback ,
I left 2 comments.

In general I agree with the refactoring. Look nice!

**Comment by timonback** [comment]
> I left 2 comments

Great, I am curious. @aerfus can you publish/comment your review. I cant see your comments yet. Do your comments still have the 'pending' tag?

**Review by aerfus — CHANGES_REQUESTED** [review]

**Review by aerfus — APPROVED** [review]

**Review by aerfus — APPROVED** [review]

**Review by aerfus — APPROVED** [review]
Reviewed. Good!

**Pull request merged**
