### PR TITLE
feat: interceptor filter pattern for serialization/deserialization common cases such as Message and KStream 

### PR DESCRIPTION
**Pull request by SheheryarAamir**
Implement the interceptor filter pattern. Each type has its own class (message, kstream, ...). This allows users to specify their own or (de)activate them. And it opens up the extension point via bean injection and ordering

Relates to https://github.com/springwolf/springwolf-core/issues/433

### CODE REVIEW

**Comment by timonback** [comment]
Hi @SheheryarAamir 
@sam0r040 and I started on it by converting the SpringPayloadExtractor in core to a spring bean.

The idea is that List-Extractor, Message- (and KStream- in cloud-stream) would implement the newly introduced interface.
The SpringPayloadExtract finds them via dependency injection (List<PayloadExtractor>).

This might be a bit more tricky than expected.
Next steps would be:
- Create a class for the KStream- & Message- each and implement the interface
- Adapt the SpringPayloadExtract (if needed)

Right now, we are unsure about the best solution.

We can also imagine a single class that does handle all GenericTypes in one. And similar to resilience4j.ignoreException, a user can set the types which should be extracted via configuration:
```properties
springwolf:
    ...:
        payloadExtractor:
            types:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
```

**Comment by SheheryarAamir** [comment]
thank you @timonback. I have one question, how to extract payload type in we are using custom interface instead of `spring message` for example `MyMessage<String>` ?

**Comment by timonback** [comment]
Hi, sorry I forgot to update and good question.

I am not sure if the current state is the final idea before the release. I imagine that the map of classes that can be extracted can be passed via properties configuration by the user.
The map is likely also missing some entries. Function, Consumer and Supplier comes to mind. Are you missing some entries?

**Comment by SheheryarAamir** [comment]
No, I dont think of any more entries other than already mentioned. But giving an option to user to put values in map solve most of the problem.
I also like the `fasterxml` implementation of deserialisers . You can have a look in class `SimpleDeserializers` of `jackson-databind:2.15.2` library

**Pull request merged**
