### PR TITLE
Feat/adds markdown support

### PR DESCRIPTION
**Pull request by robert-henke**
Hi, this pull request considers the requested markdown support described in https://github.com/springwolf/springwolf-core/issues/542 . It uses ngx-markdown with enabled mermaid and prismjs support. It allows to use markdown syntax in all description fields.

### CODE REVIEW

**Comment by timonback** [comment]
Thank you @robert-henke for this contribution!

To showcase this on our demo website, it is best to also update at least the description of the examples/kafka-example application as well. The new description could be something like the existing one, new line, ˋmarkdownˋ syntax is _supported_ as well. (I am open for creative suggestions as well)
Possibly showcase also a line of code as you included prism?
Can you do that?

Do you know how prism compares to highlightjs, which we already use to render json?

Mermaid is a larger dependency, so I am hesitant to include it just because ngx-markdown supports it. Do you have a specific case in mind, where you want to visualize a diagram in the info section and/or the channels?

**Comment by robert-henke** [comment]
Hi @timonback  I added some example texts for the description fields. Let me know if the provided examples meet your expectations.

Considering the mermaid lib: We would like to add some flow charts and / or sequence diagrams to document message flows between services. However, this is not essential for us, as we could simply include an image with the diagram. It would just be nice to have a single source of code for further adaptations of diagrams etc.

The prismjs lib is used by ngx-markdown to highlight code fragments inside code blocks. I could not find a (documented) way to use highlightjs for this purpose. That is why I included the prismjs dependency as well. The lib is used by markdown by simply adding the required language as part of a text block syntax in markdown (e.g. `\`\`\`json `). I included an example for code highlighting as well.

**Comment by robert-henke** [comment]
Hi @timonback I adapted the json file as proposed, I also had to add some minor adjustments to the `OpenApiGeneratorSystemTest`. The kafka example test target should run without errors now. Let me know of any other required adjustments.

From my (limited) understanding of prismjs and the current use of highlightjs I could imagine that it is absolutely possible to realize those use-cases with prismjs as well.

**Comment by timonback** [comment]
We decided to remove mermaid support as the dependency because we are unsure about the use-case. To us, it seems like that you try to document something that should be located in other tools (Confluent, Backstage, ApiHub) that gives a broad overview over all services - not a single one).

Also, the dependency is rather large and as soon as we add it, we will have to support it forever.

---

Still, thank you for this very nice addition and the work you have put into it. It will be part of the next release 🚀

**Pull request merged**
